config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  resources :calories
  resources :share_tokens, only: :create
  devise_for :users, controllers: {registrations: 'registrations'}
  get 'send_progress', to: 'send_progress#index' 
  post '/send_email', to: 'send_progress#send_email', as: :send_progress_email
  get "calories?token=#{@token}", to: 'share_graphs#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calory.rb
class Calory < ApplicationRecord
    belongs_to :user

    validates :value, :type_value, :comment, presence: true
    validates :comment, length: { maximum: 250, too_long: "%{count} characters is the maximum allowed. "}
    validates :value, numericality: true

    default_scope {order("created_at desc")}

    TYPE_VALUE = %w{ lost won }

    def self.total_grouped_by_day(time_ago)
        # calories = current_user.calories.where(created_at: time_ago.beginning_of_day..Time.now)
        calories = self.where("created_at > ?", time_ago.to_date)
        calories = calories.group("created_at")
        calories = calories.select("created_at, sum(value) as total_value")
        calories.group_by { |c| c.created_at.to_date} 
    end

    def self.search(date,comment)
        if !date.blank? and !comment.blank?
            where(["created_at::TIMESTAMP::DATE = ? and comment LIKE ?", date ,"%#{comment}%"])
          elsif !comment.blank?
            where(["comment LIKE ?", "%#{comment}%"])
          elsif !date.blank?
            where(["created_at::TIMESTAMP::DATE = ?", date])
          else
            self.all
        end
    end

    # scope :search_date, ->(date) {where(["created_at::TIMESTAMP::DATE = ?", date])} if !date.blank?
    # scope :search_comment, ->(comment) {where(["comment LIKE ?", "%#{comment}%"])} if !comment.empy?
    # scope :search_both, ->(date,comment) {search_date.search_comment} if !date.blank? and !comment.blank?
end

app/models/share_token.rb
class ShareToken < ApplicationRecord
  belongs_to :user
  attr_accessor :token, :expires_at
  before_save :generate_token

  def generate_token
     self.token = SecureRandom.urlsafe_base64 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :calories
  has_many :share_tokens
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calories_controller.rb
class CaloriesController < ApplicationController
  before_action :set_calory, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  after_action :update_reister_numbers_to_user, only: [:create, :destroy]

  # GET /calories
  # GET /calories.json
  def index
    date = params[:search_date]
    comment = params[:search_comment]
    @calories = current_user.calories.search(date,comment).page(params[:page]).per(15)
  end
  # GET /calories/1
  # GET /calories/1.json
  def show
    @calory = Calory.find(params[:id])
  end

  # GET /calories/new
  def new
    @calory = current_user.calories.new
  end

  # GET /calories/1/edit
  def edit
    @calory = Calory.find(params[:id])
  end

  # POST /calories
  # POST /calories.json
  def create
    @calory = current_user.calories.new(calory_params)

    respond_to do |format|
      if @calory.save
        format.html { redirect_to @calory, notice: 'Calory was successfully created.' }
        format.json { render :show, status: :created, location: @calory }
      else
        format.html { render :new }
        format.json { render json: @calory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calories/1
  # PATCH/PUT /calories/1.json
  def update
    respond_to do |format|
      if @calory.update(calory_params)
        format.html { redirect_to @calory, notice: 'Calory was successfully updated.' }
        format.json { render :show, status: :ok, location: @calory }
      else
        format.html { render :edit }
        format.json { render json: @calory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calories/1
  # DELETE /calories/1.json
  def destroy
    @calory.destroy
    respond_to do |format|
      format.html { redirect_to calories_url, notice: 'Calory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calory
      @calory = Calory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calory_params
      params.require(:calory).permit(:value, :type_value, :comment, :user_id, :search_date, :search_comment)
    end

    def update_reister_numbers_to_user
      new_number = current_user.calories.pluck(:id).size
      User.find(current_user.id).update(num_register: new_number)
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private   
    def sign_up_params
     params.require(:user).permit(:email, :password, :password_confirmation)
    end
   
    def account_update_params
     params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
    end
end

app/controllers/send_progress_controller.rb
class SendProgressController < ApplicationController
    def index 
    end

    def send_email
        somebody = params[:email]
        @token = current_user.share_token.create(expires_at: Time.now + 24.hours)
        ShareMyProgressMailer.send_to_some_email(somebody).deliver_now
        redirect_to(calories_path, notice: 'Graphic shared')
    end
 
end

app/controllers/share_graphs_controller.rb
class ShareGraphsController < ApplicationController
    before_filter :check_token
  
    def check_token
      redirect_to :back, flash: {error: "Bad link"} 
      if current_user.share_token.token.where("token = ? and expires_at > ?", params[:token], Time.now).first.present?
    end
  
    def show
      redirect_to calories_path
    end
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calories_helper.rb
module CaloriesHelper

  def calory_author(calory)
    user_signed_in? && current_user.id == calory.user_id
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/render_calories_helper.rb
module RenderCaloriesHelper

  def calories_data
    time_ago = 1.months.ago
    # calories_by_day = current_user.calories.total_grouped_by_day(time_ago)
    calories_won_by_day = current_user.calories.where(type_value: "won").total_grouped_by_day(time_ago)
    calories_lost_by_day = current_user.calories.where(type_value: "lost").total_grouped_by_day(time_ago)

    (time_ago.to_date..Date.today).map do |day|
      {
      created_at: day,
      # value: complete_nil_fields(calories_by_day[day]),
      won: complete_nil_fields(calories_won_by_day[day]),
      lost: complete_nil_fields(calories_lost_by_day[day])
      }
    end
  end

  def complete_nil_fields(calory)
    calory.nil? ? 0 : calory.first.try(:total_value)
  end

end

app/views/calories/_form.html.erb
<div class="columns">
  <div class="column is-8 is-centered">

    <%= simple_form_for(@calory) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">

        <div class="control">
            <%= f.input :comment, 
            required: true, input_html: { class: "input" }, 
            wrapper: false, label_html: { class:"label" } %>
        </div>
      
        <div class="control"style="width:100px">
          <%= f.input :value, 
          required: true, input_html: { class: "input" }, 
          wrapper: false, label_html: { class:"label" } %>
        </div>
        
        <label style="margin-top:5px"><strong>*Type of log</strong></label>
        <div class="control has-icons-left" style="margin-top:5px">
          <span class="select">
            <%= f.input_field :type_value, collection: Calory::TYPE_VALUE, prompt: "Select type" %>
          </span>
          <span class="icon is-small is-left">
            <i class="fa fa-tag"></i>
          </span>
        </div>

      </div>

      <div class="form-actions">
        <br>
        <%= f.button :submit ,class:"button is-info" %>
      </div>

    <% end %>

  <div>
<div>

app/views/calories/edit.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Editing calory registration
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
    <%= render 'form', micropost: @calory %>
    <br>
    <%= link_to 'Back', calories_path, class:"button" %>
</div>

app/views/calories/index.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Calories progress
      </h1>
    </div>
  </div>
</section>
<% end %>


<div class="hero-body">
  <div style ="width: 1010px; padding-left:100px">
    <%= link_to  'share', send_progress_path,  class: "button" %>
    <%= content_tag :div, "", id: "calories_progress", data: {calories: calories_data } %>
  </div>
<br>
<br>
  <div class="container">
    <div class="table-container" style="width: 1010px; padding-left:50px">
    <div class="container">
      <%= form_tag(calories_path, method: :get) do %>
        <div style = "width:200px; float:left">
        <%= text_field_tag :search_date, params[:search_date],type: :date, class:"input is-link is-small" %></div>
        <div style = "width:200px; float:left">
        <%= text_field_tag :search_comment, params[:search_comment], placeholder:"exp. tomatoes", class:"input is-link is-small" %></div>
        <%= submit_tag ("Search"), class: 'button is-link is-small'%>
      <% end %>
    </div>

    <br>
    <div style="width:500px"><%= paginate @calories, window: 2 %></div>
    <br>
      <table class="table is-narrow is-hoverable -row-hover-background-color primary" >
      <thead>
        <tr>
          <th title="Comment">Comment</th>
          <th title="Type">Type</th>
          <th title="Value">Calories</th>
          <th title="Date">Date</th>
          <th title="Action">
            <div class="tag is-link is-normal">Total registers <%= current_user.num_register%></div>
          </th>
        </tr>
      </thead>
        <% @calories.each do |calory| %>
          <tbody>
          <tr>
            <td style="width: 600px;"><%= calory.comment %></td>
            <td><%= calory.type_value %></td>
            <td><%= calory.value %></td>
            <td><%= calory.created_at.strftime("%d-%m-%Y") %></td>
            <td>
              <%= link_to 'Edit', edit_calory_path(calory), class: "button is-small" %>
              <%= link_to 'Delete', calory, method: :delete, data: { confirm: "Are you sure ?" }, class: "button is-small" %>
            </td>
          </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/calories/new.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Publish your calory progress
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', micropost: @calory %>
  <br>
  <%= link_to 'Back', calories_path, class:"button" %>
</div>

app/views/calories/show.html.erb
  <div class="columns">
    <div class="column is-8">
      <p>
        <strong>Comment:</strong>
       <div class="notification" style="width: 900px; margin:0px ", wrapper: false>
        <%= @calory.comment %>
      </div>

        <strong>Value:</strong>
      <div class="notification" style="width: 900px; margin:0px ", wrapper: false>
        <%= @calory.value %>
      </div>

      <strong>Type value:</strong>
      <div class="notification" style="width: 900px; margin:0px ", wrapper: false>
        <%= @calory.type_value %>
      </div>
      </p>
        <% if calory_author(@calory) %>
          <%= link_to 'Edit', edit_calory_path(@calory), class: 'button' %>
        <% end %>

      <%= link_to 'Back', calories_path , class: 'button'%>
</div>
</div>

app/views/home/index.html.erb
<section class="hero is-info is-fullheight">
  <div class="hero-body">
    
      <p class="title">
        Wellcome to my app
      </p>
    
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My calories</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div id="notify" class="notification is-success global-notification">
        <button class="delete" onclick ="hide_flash()"></button>
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div id="notify" class="notification is-danger global-notification">
        <button class="delete" onclick ="hide_flash()"></button>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    
     <nav class="navbar is-info" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
      <% if user_signed_in? %>
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Home</h1>
        <% end  %>
        <%= link_to calories_path, class:"navbar-item" do %>
          <h1 class="title is-5">my calories</h1>
          
        <% end  %>
      <% end %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
    

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">


            <% if user_signed_in? %>
              <%= link_to 'add calorie', new_calory_path, class: "navbar-item button is-dark" %>

              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to 'Edit', edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-info" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-info"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

<% unless current_page?(root_path) %>
  <div class="container">
    <%= yield %>
  </div>
  <% else %>
  <%= yield %>
<% end %>

  </body>
  <script>
    function ocultar(){
      document.getElementById('nota').style.display = 'none';
    }
  </script>
</html>

app/views/send_progress/index.html.erb
<% content_for :header do %>
<section class="hero is-info">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Share my progress
      </h1>
    </div>
  </div>
</section>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-4">

      <%= form_tag(send_progress_email_path, method: :post) do %>
        <label> <strong>*Writte an email to share </strong></label>
        <%= text_field :email, params[:email], type: :email, class:"input"%>
        <br>
        <br>
        <%= submit_tag ("Send"), class: 'button is-link' %>
      <% end %>

        <div>
            <br>
            <br>
            <%= link_to 'Back', calories_path, class:"button" %>
        </div>

      </div>
    </div>
  </div>
</section>